# Generated by Django 4.2.6 on 2023-10-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_userinfo_data2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='data2',
        ),
    ]
