# Generated by Django 4.2.6 on 2023-10-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='data',
            field=models.IntegerField(default=6),
        ),
    ]
