# Generated by Django 4.2.6 on 2023-10-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_depart_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depart',
        ),
    ]
